### ISSUE TITLE
MProc执行没有values的Insert语句异常

### ISSUE THREAD

**Issue by zhanggangbz** [cyq1162/cyqdata#11]
sql:
INSERT INTO TABLE_NAME1 (ID,RQ,FK_ID) SELECT RAWTOHEX(SYS_GUID()),TO_CHAR(SYSDATE,'yyyy-MM-dd'),TABLE_NAME2.ID FROM TABLE_NAME2

以上语句会导致SqlSyntax.cs第161行计算出一个-1，然后第162就崩溃了

**Comment by cyq1162** [comment]
什么数据库类型？

**Comment by cyq1162** [comment]
已处理。
