### ISSUE TITLE
MDataTable.AcceptChaged方法批量插入，mySQL语句有问题

### ISSUE THREAD

**Issue by damonxx** [cyq1162/cyqdata#12]
mysql库，\SQL\SqlCreate.cs中
internal static string MySqlBulkCopySql = "LOAD DATA LOCAL INFILE '{0}' INTO TABLE {1} CHARACTER SET utf8 FIELDS TERMINATED BY '{2}' LINES TERMINATED BY '|\r\n|' {3}"; 
语句执行报错，删除 CHARACTER SET utf8就好了

**Comment by cyq1162** [comment]
不知道你是什么 版本，目前测试的版本都 没遇到这个问题，没有批定charset的中文会乱码的。
