### ISSUE TITLE
文本数据库insert中文问题

### ISSUE THREAD

**Issue by damonxx** [cyq1162/cyqdata#21]
文本数据库insert的值带有中文时，会删除已有数据，插入英文就不会

**Comment by cyq1162** [comment]
未发现该问题。请用最新版本测试是否存在有该有问题，如有，请提供demo给本人QQ：272657997

**Comment by damonxx** [comment]
> 未发现该问题。请用最新版本测试是否存在有该有问题，如有，请提供demo给本人QQ：272657997

已发您QQ邮箱，请查收

**Comment by cyq1162** [comment]
用你的demo版本，该问题是存在，引入新版源码发现已没有该问题，不过倒是发现有另一个问题（应该复盖的变成追加）。
已经修复，可升级下源码，目前源码刚升级到了V5.8.0.0，Nuget 会晚一两天同步。

**Comment by damonxx** [comment]
> 用你的demo版本，该问题是存在，引入新版源码发现已没有该问题，不过倒是发现有另一个问题（应该复盖的变成追加）。
> 已经修复，可升级下源码，目前源码刚升级到了V5.8.0.0，Nuget 会晚一两天同步。

更新到V5.8.0.0还是一样的问题呀......
多次使用形如
` using (txtDb db = new txtDb())
{
                //inser中文时有bug，多次运行程序，文本数据库只有一条记录
                db.testdate = DateTime.Now.ToString();
                db.shift = "中文";
                db.Insert();                              
}`
的方法，只有一条数据

**Comment by cyq1162** [comment]
为了方便调试，上次测试时把OrmBase改成了SimpleOrmBase，所以没用OrmBase再测试一遍。
现在问题已经解决了，是保存成xml时的编码问题，导致下次加载时会加载中文乱码而失败。
重新更新一下源码即可。
