### ISSUE TITLE
.net core下读取配置文件建议

### ISSUE THREAD

**Issue by zjadmin** [cyq1162/cyqdata#22]
![image](https://user-images.githubusercontent.com/11642533/52993741-3738ad00-3450-11e9-90f6-2d119932f21d.png)

**Comment by cyq1162** [comment]
已经支持该功能：
557：NetCore下：appsettings.json 支持指定额外的配置文件，如： {ConnectionStrings:{},AppSettings:{...}, AddtionalConfigFiles:["a.json","b.json"]}(2019-03-30)
示例：
{
  "ConnectionStrings": {
    //"Conn": "txt path={0}App_Data"
  },
  "AppSettings": {
    
  },
  "AddtionalConfigFiles": [ "appsetting2.json" ,"可以指定多个配置文件.ini"]
}
--------------
appsetting2.json 内容如下：
{
keyA:xxxx,
keyB:xxxx
}
如果额外配置文件里的key出现同名，会复盖前面的。
