### ISSUE TITLE
.net core请问配置文件 该怎么配置呢？

### ISSUE THREAD

**Issue by hanpanapn** [cyq1162/cyqdata#23]

**Comment by zjadmin** [comment]
asp.net core 配置如图：
![image](https://user-images.githubusercontent.com/11642533/53217858-a43c8480-3694-11e9-8c39-c23c946c7a3b.png)
在.net core 控制台下，我暂时没有跑起来，你如果跑起来了，请告知一下，O(∩_∩)O谢谢

**Comment by hanpanapn** [comment]
> 在.net core 控制台下，我暂时没有跑起来，你如果跑起来了，请告知一下，O(∩_∩)O谢谢

{
  "exclude": [
    "**/bin",
    "**/bower_components",
    "**/jspm_packages",
    "**/node_modules",
    "**/obj",
    "**/platforms"
  ],
  "appSettings": {
    "IsAutoCache": false
  },
  "connectionStrings": {
    "Conn": "host=102.168.1.3;port=3306;database=ddbase;uid=root;pwd=123456;Convert Zero Datetime=True;SslMode = none;Character Set=utf8"
  }
}
上面是appSettings.json配置文件,不过现在的cyq.data程序有bug ,下面是更改后的代码：
![image](https://user-images.githubusercontent.com/15027167/53222504-ff787200-36a8-11e9-9069-a64b9b870ab4.png)
[Test.zip](https://github.com/cyq1162/cyqdata/files/2892567/Test.zip)

**Comment by cyq1162** [comment]
随着.NET Core 目前更新到 .net9 ，程序目前已优化没有bug，参考的Taurus.MVC 当前版本是V3.4.6， cyq.data 当前版本是V5.9.3.1
