### ISSUE TITLE
使用Redis自动缓存，更新表数据移除缓存时报错

### ISSUE THREAD

**Issue by Kueew** [cyq1162/cyqdata#25]
AutoCache.RemoveCache(string baseKey):

 if (_MemCache.CacheType == CacheType.LocalCache)
                    {
                        if (cacheKeys.ContainsKey(baseKey))
                        {
                            keys = cacheKeys[baseKey].ToString();
                            cacheKeys.Remove(baseKey);
                        }
                    }
                    else
                    {
                        keys = _MemCache.Get<string>(baseKey);
                    }
                    if (!string.IsNullOrEmpty(keys))
                    {
                        foreach (string item in keys.Split(','))
                        {
                            _MemCache.Remove(item);
                        }
                    }
在此代码段中，keys获取出来的数据为：,K32820628561
keys值Split之后，第一个索引值为空，_MemCache.Remove时会报错。
异常信息：
Value cannot be null.
Parameter name: Key may not be empty.
   at CYQ.Data.Cache.ClientBase.checkKey(String key)
   at CYQ.Data.Cache.ClientBase.hash(String key)
   at CYQ.Data.Cache.RedisClient.Delete(String key)
   at CYQ.Data.Cache.RedisCache.Remove(String key)
   at CYQ.Data.Cache.AutoCache.RemoveCache(String baseKey)

**Comment by Kueew** [comment]
![image](https://user-images.githubusercontent.com/18065485/55340114-9caf9d00-54d6-11e9-877e-17f7ed3019f2.png)

**Comment by cyq1162** [comment]
已经做了细节处理，更新源码即可。
