### ISSUE TITLE
Redis自动缓存，获取StringBuilder值失败

### ISSUE THREAD

**Issue by Kueew** [cyq1162/cyqdata#26]
AutoCache.SetBaseKey(string baseKey, string key):
 StringBuilder sb = _MemCache.Get<StringBuilder>(baseKey);
此行代码获取出来的值为空，其实redis里面有值。
![image](https://user-images.githubusercontent.com/18065485/55343574-f5ceff00-54dd-11e9-8566-a698bbdbea78.png)
如果不能获取到之前的的key，那么在更新表数据时会导致部分缓存未清除，再次select时会读取缓存数据，而不是更新之后的数据。

**Comment by cyq1162** [comment]
已经处理，更新源码即可。
