### ISSUE TITLE
.Net Core 2.2  Cyq.Data V5.8.0.0 Can't find the connection key 'Conn' from connectionStrings config section !

### ISSUE THREAD

**Issue by Kueew** [cyq1162/cyqdata#27]
.Net Core 2.2  Cyq.Data V5.8.0.0 Can't find the connection key 'Conn' from connectionStrings config section !

经过调试源码发现，在IOHelper.ReadAllText方法中cache变量为null，导致引发NullReferenceException，所以读取配置文件失败，暂未发现cache为何为null。

配置wen文件：
![image](https://user-images.githubusercontent.com/18065485/56178329-79d3cb80-6034-11e9-8f2f-36894024da02.png)

**Comment by cyq1162** [comment]
上下文信息不够判断问题。

**Comment by yueliuhun** [comment]
检查下appsettings.json字符集是不是utf-8

**Comment by cyq1162** [comment]
问题之前的版本已解决了，忘了哪个版本了，当前最新版本V5.9.3.1
