### ISSUE TITLE
怎么样用cyqdata 将 DataTable 插入数据库中，DataTable字段和数据库表结构一样的

### ISSUE THREAD

**Issue by LiuNet2** [cyq1162/cyqdata#31]
怎么样用cyqdata 将 DataTable 插入数据库中，DataTable字段和数据库表结构一样的？

是需要foreach 一行一行action.insert吗？

 谢谢

**Comment by cyq1162** [comment]
MDataTable dt=DataTable;
dt.AcceptChange(...);

**Comment by LiuNet2** [comment]
谢谢回复，
我根据你的提示，也看了你博客的demo

 LoadData();
            if (table.Rows.Count < 1000)
            {
                //批量添加数据。
                //给table批量添加行。
                MDataRow row = null;
                for (int i = 0; i < 1000; i++)
                {
                    row = table.NewRow();
                    row.Set("id", "User:" + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss.fff"));
                   // row.Set(Users.CreateTime, DateTime.Now);
                    table.Rows.Add(row);
                }
                //调用表的批量添加。
                table.AcceptChanges(AcceptOp.Insert);


                //重新绑定到控件。
                table.Bind(gvUsers);
                gvUsers.Refresh();
            }


这样操作后，新插入的数据在grid上展示出来了，但是，数据库中没有新插入的数据？
请帮我看下，谢谢！

grid控件中有数据
![image](https://user-images.githubusercontent.com/48855867/57562597-bb069380-73c6-11e9-8eb3-754e30d750ab.png)

数据库中没有数据
![image](https://user-images.githubusercontent.com/48855867/57562606-c78aec00-73c6-11e9-8f7a-e92b0cd61233.png)

**Comment by LiuNet2** [comment]
可以了，谢谢
