### ISSUE TITLE
MAction用SetSelectColumns（）方法指定查询了查询的列后绑定datagridview 用户修改字段数据后如果数据为空批量更新将无法更新为空的数据。

### ISSUE THREAD

**Issue by MarshalT** [cyq1162/cyqdata#34]
`  public partial class Form1 : Form
    {
        MDataTable md = null;
        public Form1()
        {
            InitializeComponent();
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            string[] cName;

            cName = new string[] { "Show", "ID", "ChannelName","CustomName", "YAxisName", "Format", "Unit", "Color", "AlarmEnable" };

            using (MAction action = new MAction("ChannelTable"))
            {
                action.SetSelectColumns(cName);
                md = action.Select();
                md.Bind(dgv_ChannelEditor);
            }
        }

        private void tsb_Save_Click(object sender, EventArgs e)
        {
           
            if (md.AcceptChanges(AcceptOp.Update))
            {
                MessageBox.Show("保存成功！", "提示", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            else
            {
                MessageBox.Show("保存失败！", "错误提示", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
           
        }
    }`

MAction用SetSelectColumns（）方法指定查询了要查询的列后绑定datagridview 用户修改字段数据后如果数据为空批量更新将无法更新为空的数据。

**Comment by cyq1162** [comment]
已修正，更新源码即可：（2020-04-09）
