### ISSUE TITLE
cache对象是为空导致无法读取配置文件：appsettings.json

### ISSUE THREAD

**Issue by idragonet** [cyq1162/cyqdata#35]
![QQ截图20190906221730](https://user-images.githubusercontent.com/9882118/64434900-2736a100-d0f4-11e9-814d-666d55e93e20.jpg)

Visual Studio2017+.NET Core 2.1 + CYQ.Data 5.8.2.4

**Comment by idragonet** [comment]
Exception: V5.8.2.4 Can't find the connection key 'Conn' from connectionStrings config section !

**Comment by idragonet** [comment]
![QQ截图20190907103308](https://user-images.githubusercontent.com/9882118/64468759-efaf0f80-d15a-11e9-9f10-278d00fc6ef3.jpg)
这样改了下

**Comment by cyq1162** [comment]
之前版本已修正忘了哪个版本了，当前版本V5.9.3.1
