### ISSUE TITLE
Exception: V5.7.9.7 Can't find the connection key 'Conn' from web.config or app.config!

### ISSUE THREAD

**Issue by topstop3416** [cyq1162/cyqdata#37]
新建 .net core 3.1 web api项目

NuGet 添加 cyqdatacore

配置文件添加数据库连接
![1](https://user-images.githubusercontent.com/37021873/71657523-30bad780-2d7b-11ea-816f-07cb2170cb7d.png)

添加控制器
![image](https://user-images.githubusercontent.com/37021873/71657556-61027600-2d7b-11ea-84b0-7a7422aa3188.png)

调用报错 Exception: V5.7.9.7 Can't find the connection key 'Conn' from web.config or app.config!
![image](https://user-images.githubusercontent.com/37021873/71657637-b3dc2d80-2d7b-11ea-92fa-248172e9c7d2.png)

修改控制器 写下日志 OK了 不知道哪里的问题
![image](https://user-images.githubusercontent.com/37021873/71657708-fd2c7d00-2d7b-11ea-9b81-d99d3063fb69.png)

**Comment by cyq1162** [comment]
直接下载源码项目加载即可。nuget版本没更新那么快。

**Comment by cyq1162** [comment]
更新版本可解决，关闭问题了。
