### ISSUE TITLE
使用MAction里面的select方法，因SQL语法错，无法知道错误！

### ISSUE THREAD

**Issue by sdricky** [cyq1162/cyqdata#4]
使用MAction里面的select方法，因SQL语法错或者使用一些引起CYQ防注入的关键字时，无法知道错误！而且当查询的时候，如果打开了事务后，CYQ会因为刚才这些语法错的问题，内部释放事务，回滚，但程序继续走下去，变成SELECT方法之前的回滚，下面的继续执行，造成数据不一致的问题

**Comment by cyq1162** [comment]
设置IsWriteLog为false，（或默认不配置即可）
