### ISSUE TITLE
我创建了一个新表，但是DBTool.GetTables得到的好像是缓存的？

### ISSUE THREAD

**Issue by wo00421309** [cyq1162/cyqdata#40]
如何通过DBTool.GetTables得到刚创建这张表，谢谢

**Comment by cyq1162** [comment]
框架运行到读表的时候 ，会缓存到数据为所有表的结构。
在程序运行时，只有通过框架动态创建表才会自动调整缓存表结构相关的信息。
程序运行时，手工去修改数据库结构，是不会刷新结构的（如果要刷新，重启程序即可）
另一种方式，就是通过CacheManage缓存管理的Clear()一次性清空所有缓存。

**Comment by wo00421309** [comment]
谢谢
