### ISSUE TITLE
XHtmlAction自定义标签的使用方法有没有说明

### ISSUE THREAD

**Issue by ghostalien** [cyq1162/cyqdata#42]
XHtmlAction自定义标签的语法更新过后,有没有一个完整的说明或例子?

**Comment by cyq1162** [comment]
只是新增了一个功能，具体见我博客最新文章：https://www.cnblogs.com/cyq1162/p/12844440.html

**Comment by cyq1162** [comment]
最新的 TaurusMVC系列，使用的是XHtmlAction 模块引擎，该系列文章可以看好的展示该使用方法：https://www.cnblogs.com/cyq1162/category/2311780.html
