### ISSUE TITLE
反馈三个BUG，确定了是BUG

### ISSUE THREAD

**Issue by goophps** [cyq1162/cyqdata#45]
1 .net core环境读不到这个数据库连接字符串，读出来总是为null
<connectionStrings>
		<add name="Conn" connectionString="server=.;database=aa;uid=sa;pwd=aa;"/>
	</connectionStrings>
2 MDataTable赋值给dataGridView后，点击列标题，排序失效。用原生的DataTable则无此问题。
3 假设我数据有两张表，aa_b和 aab，程序就会报错。
错误代码是这行：return Math.Abs(name.Replace("-", "").Replace("_", "").Replace(" ", "").ToLower().GetHashCode());

**Comment by cyq1162** [comment]
1、默认utf8编码，被你修改成gb2312编码问题引发的，刚更新了源码，做兼容处理了。
2、mdt目前没对datagridview的各项功能做进一步处理，需要触发dataGridView的事件时，先用dt.ToDataTable()去绑定。
3、maction内部机制问题，做处理成同一个表。如果建表非要存在aa_b,a_ab,a_a_b这种特殊，用MProc，用原生的sql语句去处理它。
