### ISSUE TITLE
关于netcore appsettings.json 读不到conn的反馈

### ISSUE THREAD

**Issue by yueliuhun** [cyq1162/cyqdata#46]
我在实际了开发中也遇到了 appsettings.json 里读不到conn配置问题

然后我发现是因为appsettings.json的字符集问题，如果是utf-8 就没有问题
如果是gb2312 就不行（系统会提示无法识别gb2312字符集提示）

我估计那些遇到读不到配置文件的人，可能用了windows记本事去编辑了他，导致这个故障的产生

希望做个容错处理！ 或是对字符集的判断

**Comment by cyq1162** [comment]
已做处理，更新源码即可。（2020-10-12）
