### ISSUE TITLE
新建的.net core API项目  appsettings里面的 conn连接符提示不存在

### ISSUE THREAD

**Issue by goodluckjh** [cyq1162/cyqdata#49]
![A}8J B1JGP3SDCHR})}6)PC](https://user-images.githubusercontent.com/98632153/153103152-57e5bb08-942f-4b2c-83ea-db87368b1bb9.jpg)

NuGet里面引用的版本：V5.8.4.9

**Comment by cyq1162** [comment]
新版本已修复过这个问题，当前最新版本是：V5.9.3。
