### ISSUE TITLE
可不可以增加一个数据库连接加密码的功能

### ISSUE THREAD

**Issue by quejuwen** [cyq1162/cyqdata#5]
可不可以增加一个数据库连接加密码的功能?

**Comment by cyq1162** [comment]
你的需求，可以通过全局AppConfig.DB.DefaultConn=解密函数(AppConfig.GetConn("Conn"));

**Comment by cyq1162** [comment]
已增加该功能，忘了哪个版本加的了，可以配置Conn的时候，配置用 CYQ.Data.Tool.EncrypHelper 加密的链接。 当前最新V5.9.3.1
