### ISSUE TITLE
CYQ.Data.AppConfig.SetApp("aa0","10"); 这句代码报错，求救，是不是我不会使用？

### ISSUE THREAD

**Issue by goophps** [cyq1162/cyqdata#51]
![image](https://user-images.githubusercontent.com/49714224/155964095-40827248-e10e-4268-b5f8-9374aeb5e2b5.png)
开发环境是：vs2022   winform   .net6

**Comment by goophps** [comment]
app.config的读写操作，要如何使用？   
我研究半天源码，不知道如何使用。现在设置成功了，也能读取到数据，关掉再重新开就没有了，这个数据存在哪里？

**Comment by cyq1162** [comment]
如果是winform 程序，需要对 appsetting.json 右键属性，始终复制，这样配置文件才会一起生成取bin目录，才有配置文件读取，否则读不到的。
