### ISSUE TITLE
AppConfig未包含IsAspNetCore的定义

### ISSUE THREAD

**Issue by hexino** [cyq1162/cyqdata#53]
RT
![image](https://user-images.githubusercontent.com/11883946/186078633-795faf2e-1de8-42e4-8f51-1bb3d5e92338.png)
![image](https://user-images.githubusercontent.com/11883946/186078691-817ff39a-24b3-49a5-9609-a05ed76f4042.png)
AppConfig.IsAspNetCore=true,是否可以去掉了？

**Comment by cyq1162** [comment]
变更为：AppConfig.IsNetCore了。
