### ISSUE TITLE
PagerBySelectBase	这个删除了吗？怎么调用分页存储过程？

### ISSUE THREAD

**Issue by ourpages** [cyq1162/cyqdata#54]
PagerBySelectBase	MSSQL是否启用分页存储过程SelectBase，默认false
代码中这个开关注释了

**Comment by cyq1162** [comment]
框架默认已经弃用存储过程，因为它不利于跨数据库。 不过网上仍有相关的分页存储过程，具体看秋色园搜索，可以直接使用MProc操作存储过程。
