### ISSUE TITLE
JsonHelper.ToList<string> 报错：没有为该对象定义无参数的构造函数。

### ISSUE THREAD

**Issue by jiszen** [cyq1162/cyqdata#55]
/// <summary>
        ///  Convert json to Entity List
        ///  <para>将Json转换为实体列表</para>
        /// </summary>
        /// <typeparam name="T">Type<para>类型</para></typeparam>
        public static List<T> ToList<T>(string json, EscapeOp op) where T : class
        {
            return JsonSplit.SplitList<T>(json, 0, op);//减少中间转换环节。
            // return ToMDataTable(json, TableSchema.GetColumnByType(typeof(T)), op).ToList<T>();  
        }

老方法可以使用，减少中间转换环节有问题。

**Comment by cyq1162** [comment]
新版本应该优化并修正了。
