### ISSUE TITLE
MDataRow ToEntity 必须继承OrmBase或者是非Custom实体类型可用吗

### ISSUE THREAD

**Issue by jiszen** [cyq1162/cyqdata#56]
使用 mdt.Rows[0].ToEntity<T>() 转换时，T是派生类（用户自定义类），只能转换派生类中的属性：
FastToT<T>.EmitHandle emit = FastToT<T>.Create();
return emit(this);
如果使用这个方法就可以，基类也可以转换：
return (T)ToEntity(typeof(T));
是否可以不继承OrmBase并且Custom类型也可用？

**Comment by cyq1162** [comment]
MDataRow ToEntity 是可以对任何实现转换的，没有其它限制，如果有，可能旧版本的bug，当前版本（目前最新V5.893）已对所有的类型转换进行了重写，应该不存在这个问题。
