### ISSUE TITLE
支持批量插入或是更新吗？

### ISSUE THREAD

**Issue by mgh2008** [cyq1162/cyqdata#9]
如题，支持大批量插入或是更新吗？

**Comment by cyq1162** [comment]
支持，MDataTable的AcceptChaged方法，支持批量插入、更新、删除。

**Comment by damonxx** [comment]
mysql利用MDataTable.AcceptChanges(AcceptOp.Insert)向表 'xxxx' 批量插入数据时，若数据库中已存在表'xxxx'，会有错误:
Error on DataOperator:Call Function::ExeNonQuery():Table 'xxxx' already exists

**Comment by cyq1162** [comment]
该问题新版本应该修正了。
